name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

  # Allows manual triggers from GitHub Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub 🚀
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Push to your Hugging Face Space Git repository
          # Update the space name if it is different from "ClearSky-AI"
          git push --force https://ArijitKRoy:$HF_TOKEN@huggingface.co/spaces/ArijitKRoy/clear-sky-ai main
